import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ExpressionOfDemand from "./ExpressionOfDemand";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>future, made.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>future, made.</h1>

        <p className={styles.description}>
          <span style={{ fontStyle: "italic" }}>not really ~ </span> we can
          always shape it forward.
        </p>

        <div className={styles.grid}>
        <a href="https://vimeo.com/526183104" className={styles.card}>
          <p>
            A demand-aware approach for the age of prosumers. Constants over
            predictions for capacity and accessibility.{" "}
              see it in action ~{">"}
          </p>
            </a>

          <div href="https://nextjs.org/learn" className={styles.card}>
            <h2>what? &rarr;</h2>
            <p>
              consumers get to say what they need, and able to offer skill-time
              as an alternative way of payment.{" "}
            </p>
          </div>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>how come? &rarr;</h2>
            <p>
              expressions of potential interest on a product, a proactive
              offering of self terms and conditions.
            </p>
          </a>

          <a
            href="/ExpressionOfDemand"
            className={styles.whyMattersCard}
          >
            <h2>why matters? &rarr;</h2>
            <p>
              current ads biz is based on collection of historical data to sell
               predictions. <br></br> this, legitimize the de-facto corporate surveilance by design.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by intuitions
         
        </a>
      </footer>
    </div>
  );
}
